"""Catálogo recuperado de material legado.

Os itens abaixo não são conhecimento puro, resposta pronta nem prova. São
candidatos de reconstrução para o MotorMatematica. O conteúdo antigo não foi
copiado como autoridade; somente os temas foram preservados para não perder
trabalho potencial.
"""
from __future__ import annotations

CANDIDATOS_FORMULAS = (
    'Fórmula de Bhaskara',
    'Teorema de Pitágoras',
    'Produto notável: quadrado da soma',
    'Diferença de quadrados',
    'Soma de Gauss',
    'Área do círculo',
    'Perímetro da circunferência',
    'Volume da esfera',
    'Volume do cone',
    'Área da superfície esférica',
    'Probabilidade clássica de Laplace',
    'Média aritmética',
    'Variância',
    'Distribuição binomial',
    'Binómio de Newton',
    'Fórmula de Euler',
    'Identidade de Euler',
    'Pequeno Teorema de Fermat',
    'Derivada de x^n',
    'Derivada do seno',
    'Regra do produto',
    'Regra da cadeia',
    'Regra de L’Hôpital',
    'Integral de x^n',
    'Integral da exponencial',
    'Integral por partes',
    'Lei dos senos',
    'Lei dos cossenos',
    'Seno da soma',
    'Identidade trigonométrica fundamental',
    'Determinante 2x2',
    'Expansão de Laplace',
    'Soma da PG infinita',
    'Série de Taylor',
    'Gradiente',
    'Teorema de Green',
    'Teorema de Stokes',
    'Fórmula de Moivre',
    'Raízes da unidade',
)

CANDIDATOS_MONOGRAFIAS = (
    'O Teorema de Gauss-Bonnet: Da Superfície Clássica à Forma de Chern',
    'O Teorema Espectral: Fundamentos Matemáticos e Aplicações à Mecânica Quântica',
    'A Prova da Conjectura de Poincaré via Fluxo de Ricci',
    'O Teorema de Riemann-Roch para Curvas Algébricas: Demonstração e Aplicações',
    'Correspondência de Langlands: Do Corpo dos Números Racionais às Formas Automórficas',
    'O Teorema do Índice de Atiyah-Singer e Suas Aplicações à Geometria e Topologia',
    'Formalismo Termodinâmico: Medidas de Gibbs, Entropia e Pressão Topológica',
    'Reticulados e Criptografia Pós-Quântica: O Problema LWE e Suas Aplicações',
    'Regularidade de Soluções de Equações Elípticas: O Teorema de De Giorgi-Nash-Moser',
    'K-Teoria de C*-Álgebras e Aplicações à Geometria Não Comutativa',
)

CANDIDATOS_PROBLEMAS_ABERTOS = (
    'Baum-Connes com coeficientes',
    'Conjectura de Ulam',
    'Kähler-Einstein em variedades de Fano',
    'Poincaré suave em dimensão 4',
    'Navier-Stokes 3D regularidade global',
    'Conjectura de Schanuel',
    'Invariância topológica da K-teoria algébrica',
    'Conjectura de Novikov',
    'Geodésicas fechadas infinitas',
    'Atiyah sobre cohomologia de variedades de representações',
    'Conjectura de Hodge',
    'Hipótese de Riemann',
    'Birch e Swinnerton-Dyer',
    'Conjectura de Tate',
    'Yang-Mills e gap de massa',
    'Goldbach forte',
    'Primos gémeos',
    'Curvatura escalar prescrita',
    'HKR em caso singular',
    'Classificação geral de C*-álgebras simples',
    'P versus NP',
    'Collatz',
    'Números perfeitos ímpares',
    'Riemann generalizada',
    'Serre sobre multiplicidades',
    'Baum-Connes para grupos com torção',
    'Bost/Boltzmann regularidade',
    'Métricas de Einstein',
    'Langlands geral',
    'Seção de Grothendieck',
    'P versus NP aplicado',
    'Segurança RSA clássica',
    'Gap espectral quântico',
    'Superalinhamento de IA',
    'Inferência causal completa',
    'Limites da aprendizagem profunda',
    'Criptografia pós-quântica ótima',
    'Parada ótima em finanças',
    'Consenso blockchain escalável',
    'Aprendizagem não estacionária',
    'Product-Market Fit universal',
    'Crescimento viral tipping point',
    'Matching ótimo em marketplaces',
    'Precificação dinâmica competitiva',
    'Churn com intervenção',
    'Adoção sem histórico análogo',
    'Portfólio de produtos',
    'Timing de entrada no mercado',
    'Incentivos em plataformas',
    'Previsão de tendências emergentes',
    'P versus NP',
    'Hipótese de Riemann',
    'Conjectura de Hodge',
    'Yang-Mills gap',
    'Navier-Stokes regularidade',
    'Birch e Swinnerton-Dyer',
    'Goldbach forte',
    'Conjectura de Beal',
    'Primos gémeos',
    'Erdős sobre progressões',
)

CANDIDATOS_APLICADOS = (
    'Classificação de Kirchberg-Phillips para C*-álgebras nucleares simples puramente infinitas',
    'Fórmula do traço de Selberg para superfícies compactas de curvatura negativa constante',
    'Navier-Stokes incompressível em R3 com dado H^{1/2}: existência e unicidade local forte',
    'Medida de Wiener e fórmula de Feynman-Kac para Schrödinger',
    'Grupos de homotopia estáveis pi_n^S(S0) para n <= 10 via Adams',
    'Riemann-Roch para variedades projetivas via K-teoria algébrica',
    'Convergência do fluxo de Ricci em superfícies fechadas',
    'KdV global em L2(R) por métodos espectrais',
    'Móduli de fibrados estáveis sobre curva algébrica',
    'Mostow rigidez para reticulados em grupos de Lie semissimples rank >= 2',
    'Classificação equivarante de Kirchberg-Phillips para ações de grupos finitos',
    'Cohomologia de Hochschild de álgebras de caminhos de quivers com relações',
    'Blow-up para NLS crítica em dimensão 2',
    'Medidas invariantes para fluxos geodésicos em curvatura negativa variável',
    'Langlands geométrico para GL(n) sobre curvas',
    'Dimensão de Hausdorff de atratores parcialmente hiperbólicos',
    'Conjectura de Zimmer em dimensão baixa',
    'Regularidade C-infinito para elípticas com coeficientes VMO',
    'Integração em caminhos com Wiener para operadores de Dirac',
    'K-teoria torcida de C*-álgebras de grupoides e defeitos topológicos',
    'Contraexemplo Baum-Connes com coeficientes',
    'Novo invariante quântico para nós via categorias de fusão modulares',
    'Ondas viajantes para reação-difusão com difusão cruzada',
    'Classificação de álgebras de Hopf semissimples finito-dimensionais',
    'Espectro de Laplace-Beltrami em variedades assintoticamente hiperbólicas',
    'FHE baseado em reticulados ideais eficiente',
    'Conjectura de Hodge para Calabi-Yau 4 particulares',
    'Cohomologia para stacks diferenciáveis',
    'Estabilidade assintótica para Boltzmann com potenciais suaves',
    'Métodos numéricos de alta ordem para EDPs estocásticas com ruído multiplicativo',
    'Previsão de séries temporais Fourier + LSTM sem dependências externas',
    'Convergência de SGD sob Polyak-Lojasiewicz',
    'Preço de opção asiática com volatilidade estocástica e Monte Carlo antitético',
    'Kyber/ML-KEM: protocolo e segurança',
    'Logística 10 armazéns e 500 clientes por MILP',
    'CNN para imagens médicas AUC > 0,95',
    'Transformer para tradução automática com perplexidade e BLEU',
    'Simular Shor para fatorar 21 sem Qiskit',
    'VaR com cópulas Gaussianas e t-Student',
    'Segurança de Proof-of-Stake contra nothing-at-stake',
    'Retenção SaaS por análise de coorte',
    'Preço ótimo por elasticidade-preço',
    'Recomendação por fatorização de matrizes SVD',
    'ARIMA-SARIMA para vendas sazonais e stock',
    'Fraude por Isolation Forest',
    'Segmentação RFM com K-means ou DBSCAN',
    'A/B test com poder 80% e MDE 2%',
    'Churn prediction com recall > 0,85',
    'Rotas urbanas 50 pontos por genético/simulated annealing',
    'CLV e CAC para sustentabilidade de startup',
)

def todos_candidatos() -> tuple[str, ...]:
    return tuple(dict.fromkeys(
        CANDIDATOS_FORMULAS + CANDIDATOS_MONOGRAFIAS
        + CANDIDATOS_PROBLEMAS_ABERTOS + CANDIDATOS_APLICADOS
    ))
