"""Currículos iniciais por pacotes.

Os pacotes são pequenos de propósito. O motor pode depois inserir pacotes
intermediários sem destruir a ordem já existente.
"""
from __future__ import annotations

from .tipos import PacoteConhecimento


def _p(
    codigo: str,
    area: str,
    nivel: int,
    titulo: str,
    objetivo: str,
    pre_requisitos: tuple[str, ...],
    palavras_chave: tuple[str, ...],
    passos: tuple[str, ...],
    explicacao: str,
    exemplos: tuple[str, ...],
    exercicios: tuple[str, ...],
    desmontagem: tuple[str, ...],
    melhorias: tuple[str, ...] = (),
) -> PacoteConhecimento:
    return PacoteConhecimento(
        codigo=codigo,
        area=area,
        nivel=nivel,
        titulo=titulo,
        objetivo=objetivo,
        pre_requisitos=pre_requisitos,
        palavras_chave=palavras_chave,
        passos=passos,
        explicacao=explicacao,
        exemplos=exemplos,
        exercicios=exercicios,
        desmontagem=desmontagem,
        melhorias=melhorias,
    )


PACOTES_MATEMATICA: tuple[PacoteConhecimento, ...] = (
    _p(
        "MAT-000",
        "matematica",
        0,
        "Nada e alguma coisa",
        "Perceber a diferença entre vazio e presença.",
        (),
        ("nada", "algo", "vazio", "objeto"),
        ("Olhe.", "Veja vazio.", "Coloque um objeto.", "Compare."),
        "Antes de contar, a pessoa precisa perceber se há alguma coisa ou se não há nada. Esse é o primeiro chão da matemática: presença e ausência.",
        ("Mesa vazia: nada. Mesa com uma pedra: alguma coisa.",),
        ("Mostre uma mão vazia.", "Coloque um lápis na mesa.", "Diga onde há algo e onde não há."),
        (
            "Nada não é um número ainda; é uma situação sem objeto.",
            "Alguma coisa também não é contagem ainda; é só presença.",
            "Quando a presença fica estável, podemos começar a separar um objeto.",
        ),
        ("Criar imagens e objetos manipuláveis.", "Adicionar verificação oral."),
    ),
    _p(
        "MAT-001",
        "matematica",
        1,
        "Igual e diferente",
        "Reconhecer quando duas coisas parecem iguais ou não.",
        ("MAT-000",),
        ("igual", "diferente", "comparar"),
        ("Pegue dois objetos.", "Olhe uma qualidade.", "Compare.", "Diga igual ou diferente."),
        "Comparar é escolher uma característica e olhar duas coisas por essa característica. Duas tampas podem ser iguais na cor e diferentes no tamanho.",
        ("Dois círculos vermelhos são iguais na cor. Um círculo vermelho e um azul são diferentes na cor.",),
        ("Ache dois objetos da mesma cor.", "Ache dois objetos de tamanhos diferentes.", "Diga a característica usada."),
        (
            "Não existe igual absoluto para tudo no começo.",
            "Primeiro escolhemos uma qualidade: cor, forma, tamanho, posição.",
            "Depois dizemos se há igualdade ou diferença nessa qualidade.",
        ),
    ),
    _p(
        "MAT-002",
        "matematica",
        2,
        "Um e muitos",
        "Separar uma unidade de um grupo.",
        ("MAT-001",),
        ("um", "muitos", "unidade", "grupo"),
        ("Aponte um.", "Aponte muitos.", "Separe um.", "Junte de novo."),
        "Uma unidade é uma coisa tratada sozinha. Muitos é quando há mais de uma coisa no campo de atenção.",
        ("Um botão na mão. Muitos botões no copo.",),
        ("Separe uma moeda.", "Mostre muitas moedas.", "Volte a moeda para o grupo."),
        (
            "A unidade nasce por escolha.",
            "O grupo nasce por reunião.",
            "Contar só vem depois de conseguir separar unidades.",
        ),
    ),
    _p(
        "MAT-003",
        "matematica",
        3,
        "Parear objetos",
        "Ligar um objeto a outro objeto para comparar grupos.",
        ("MAT-002",),
        ("par", "ligar", "correspondência"),
        ("Escolha um objeto.", "Ligue a outro.", "Repita.", "Veja se sobrou."),
        "Parear é formar ligações um-a-um. Antes de saber números grandes, já podemos saber se dois grupos têm a mesma quantidade vendo se sobra algo.",
        ("Três copos e três tampas: cada copo recebe uma tampa, não sobra nada.",),
        ("Pareie colheres e pratos.", "Veja se sobra colher.", "Veja se sobra prato."),
        (
            "Cada objeto do primeiro grupo procura um parceiro.",
            "Se todos acham parceiro e nada sobra, os grupos combinam.",
            "Se sobra, um grupo tem mais.",
        ),
    ),
    _p(
        "MAT-004",
        "matematica",
        4,
        "Contar",
        "Dar uma palavra de número para cada unidade, em ordem.",
        ("MAT-003",),
        ("contar", "ordem", "número", "último"),
        ("Toque um objeto.", "Fale um número.", "Não pule.", "O último diz quanto."),
        "Contar é parear objetos com palavras de número. Cada objeto recebe uma palavra, e a última palavra falada indica a quantidade do grupo.",
        ("Pedras: uma, duas, três. A última palavra é três; há três pedras.",),
        ("Conte três lápis.", "Conte quatro dedos.", "Explique por que não pode contar o mesmo objeto duas vezes."),
        (
            "A ordem das palavras precisa ficar estável.",
            "Cada objeto recebe uma palavra só.",
            "A última palavra resume o tamanho do grupo.",
        ),
    ),
    _p(
        "MAT-005",
        "matematica",
        5,
        "Ordem",
        "Entender antes, depois, primeiro e último.",
        ("MAT-004",),
        ("antes", "depois", "primeiro", "último", "sequência"),
        ("Faça uma fila.", "Marque o primeiro.", "Marque o próximo.", "Ache o último."),
        "A ordem aparece quando os elementos ficam em sequência. Ela permite dizer quem vem antes, quem vem depois e onde continuar.",
        ("Na fila A, B, C: A vem antes de B; C vem depois de B.",),
        ("Organize três objetos em fila.", "Troque a ordem.", "Diga o primeiro e o último."),
        (
            "Sem ordem, há grupo.",
            "Com ordem, há caminho.",
            "Contagem usa ordem nas palavras e nos objetos tocados.",
        ),
    ),
    _p(
        "MAT-006",
        "matematica",
        6,
        "Juntar",
        "Perceber adição como reunião de grupos.",
        ("MAT-005",),
        ("juntar", "reunir", "total", "adição"),
        ("Pegue um grupo.", "Pegue outro.", "Junte.", "Conte o total."),
        "Juntar é colocar grupos no mesmo campo. A adição nasce quando contamos o total depois da reunião.",
        ("Duas pedras e uma pedra juntas viram três pedras.",),
        ("Junte 1 lápis com 2 lápis.", "Junte 2 tampas com 2 tampas.", "Conte o total."),
        (
            "Primeiro existem grupos separados.",
            "Depois fazemos uma reunião.",
            "O total é contado no grupo reunido.",
        ),
    ),
    _p(
        "MAT-007",
        "matematica",
        7,
        "Retirar",
        "Perceber subtração como tirar parte de um grupo.",
        ("MAT-006",),
        ("retirar", "sobrar", "tirar", "subtração"),
        ("Comece com um grupo.", "Retire uma parte.", "Olhe o que saiu.", "Conte o que sobrou."),
        "Retirar é separar uma parte de um grupo. A subtração nasce quando perguntamos quanto ficou depois da retirada.",
        ("Cinco pedras na mesa. Tiramos duas. Sobram três.",),
        ("Comece com 4 objetos e retire 1.", "Comece com 5 objetos e retire 2.", "Conte o que sobrou."),
        (
            "Há um grupo inicial.",
            "Uma parte sai.",
            "O resto é o que permanece.",
        ),
    ),
    _p(
        "MAT-008",
        "matematica",
        8,
        "Comparar quantidades",
        "Dizer se um grupo tem mais, menos ou a mesma quantidade.",
        ("MAT-007",),
        ("mais", "menos", "mesma quantidade", "comparação"),
        ("Faça dois grupos.", "Pareie.", "Veja sobras.", "Diga mais, menos ou igual."),
        "Comparar quantidades é usar pareamento ou contagem para decidir a relação entre dois grupos.",
        ("Quatro copos e três tampas: uma tampa falta; há mais copos que tampas.",),
        ("Compare 3 lápis e 2 borrachas.", "Compare 4 tampas e 4 copos.", "Explique o que sobrou."),
        (
            "A comparação não precisa começar por símbolo.",
            "O pareamento mostra sobras.",
            "As palavras mais, menos e igual resumem o resultado.",
        ),
    ),
    _p(
        "MAT-009",
        "matematica",
        9,
        "Forma e posição",
        "Reconhecer formas simples e relações de lugar.",
        ("MAT-008",),
        ("forma", "posição", "dentro", "fora", "perto", "longe"),
        ("Olhe a forma.", "Nomeie.", "Mova.", "Diga a posição."),
        "A matemática também organiza espaço. Forma responde 'como é?'; posição responde 'onde está?'.",
        ("A bola está dentro da caixa. O cubo está fora.",),
        ("Coloque um objeto dentro de uma caixa.", "Desenhe um círculo.", "Diga o que está perto e longe."),
        (
            "Forma é uma propriedade do objeto.",
            "Posição é uma relação entre objeto e lugar.",
            "Geometria nasce quando forma e posição viram estudo.",
        ),
    ),
    _p(
        "MAT-010",
        "matematica",
        10,
        "Contar além de dez",
        "Estender a contagem para além de dez, mantendo a mesma ordem estável de palavras.",
        ("MAT-009",),
        ("onze", "doze", "contar", "além", "dez"),
        ("Conte até dez.", "Continue: onze, doze, treze...", "Não pule nenhum número.", "Pare no número pedido."),
        "Depois de dez, a contagem não recomeça do zero: continua na mesma ordem, só com nomes novos até vinte. A regra de contar (uma palavra por objeto, sem pular) continua a mesma do pacote MAT-004.",
        ("Onze lápis são dez lápis mais um lápis.",),
        ("Conte de um até quinze em voz alta.", "Conte quatorze objetos.", "Diga o número que vem depois de dezanove."),
        (
            "Dez já é uma quantidade estável.",
            "Depois de dez, cada número soma mais um, como antes.",
            "A ordem nunca pode pular ou repetir um número.",
        ),
    ),
    _p(
        "MAT-011",
        "matematica",
        11,
        "Dezena",
        "Reconhecer que dez unidades formam uma dezena, base para números maiores.",
        ("MAT-010",),
        ("dezena", "unidade", "grupo de dez", "agrupar"),
        ("Junte dez unidades.", "Chame esse grupo de uma dezena.", "Veja quantas dezenas há.", "Veja quantas unidades sobram."),
        "Uma dezena é um grupo de dez unidades. Agrupar em dezenas ajuda a contar quantidades maiores sem contar uma a uma.",
        ("Vinte e três lápis são duas dezenas e três unidades.",),
        ("Agrupe 17 objetos em dezenas e unidades.", "Diga quantas dezenas há em 30 objetos.", "Monte um grupo de 25 objetos usando dezenas."),
        (
            "Contar de um em um funciona, mas fica lento para números grandes.",
            "Agrupar de dez em dez organiza a contagem.",
            "Cada número passa a ter uma parte de dezenas e uma parte de unidades.",
        ),
    ),
    _p(
        "MAT-012",
        "matematica",
        12,
        "Juntar com reagrupamento",
        "Juntar quantidades cuja soma das unidades passa de dez, formando uma nova dezena.",
        ("MAT-011",),
        ("juntar", "reagrupar", "nova dezena", "levar um"),
        ("Junte as unidades.", "Se passar de dez, forme uma nova dezena.", "Junte as dezenas.", "Diga o total."),
        "Quando juntar as unidades passa de dez, dez dessas unidades viram uma dezena nova, que se junta às dezenas já existentes. Isto é 'juntar com reagrupamento', uma continuação do pacote MAT-006.",
        ("8 mais 5: as unidades somam 13; isso é uma dezena e três unidades.",),
        ("Junte 9 e 4.", "Junte 17 e 6.", "Explique por que 13 unidades viram uma dezena e três unidades."),
        (
            "Juntar unidades pode passar de dez.",
            "Dez unidades sempre podem virar uma dezena nova.",
            "O total final soma dezenas com dezenas e unidades com unidades.",
        ),
    ),
    _p(
        "MAT-013",
        "matematica",
        13,
        "Retirar com reagrupamento",
        "Retirar uma quantidade maior que as unidades disponíveis, desfazendo uma dezena.",
        ("MAT-012",),
        ("retirar", "desfazer dezena", "emprestar", "reagrupar"),
        ("Veja se há unidades suficientes.", "Se não houver, desfaça uma dezena em dez unidades.", "Retire o que falta.", "Diga o que sobrou."),
        "Quando não há unidades suficientes para retirar, desfazemos uma dezena em dez unidades novas. É o mesmo pacote MAT-007 (retirar), só que agora pode precisar desfazer um grupo primeiro.",
        ("22 menos 5: não há 5 unidades em 2; desfazemos uma dezena, ficam 12 unidades, e 12 menos 5 é 7; sobra uma dezena e sete unidades, ou seja, 17.",),
        ("Calcule 22 menos 5 desfazendo uma dezena.", "Calcule 31 menos 8.", "Explique por que às vezes é preciso desfazer uma dezena."),
        (
            "Retirar só é direto quando há unidades suficientes.",
            "Sem unidades suficientes, uma dezena empresta dez unidades.",
            "O resultado ainda é dezenas e unidades, só reorganizado.",
        ),
    ),
    _p(
        "MAT-014",
        "matematica",
        14,
        "Multiplicação como grupos iguais",
        "Reconhecer multiplicação como juntar vários grupos do mesmo tamanho.",
        ("MAT-013",),
        ("multiplicar", "grupos iguais", "vezes", "total"),
        ("Escolha o tamanho do grupo.", "Escolha quantos grupos.", "Junte todos os grupos.", "Conte o total."),
        "Multiplicar é juntar vários grupos do mesmo tamanho, em vez de grupos diferentes como em MAT-006. Três grupos de quatro é o mesmo que 4+4+4.",
        ("3 grupos de 4 lápis: 4+4+4 = 12 lápis.",),
        ("Monte 4 grupos de 2 objetos e conte o total.", "Escreva 3 vezes 5 como uma soma repetida.", "Calcule 2 grupos de 6."),
        (
            "Juntar grupos diferentes é adição comum.",
            "Juntar grupos iguais tem um atalho: multiplicar.",
            "Multiplicar não é um conceito novo, é adição repetida organizada.",
        ),
    ),
    _p(
        "MAT-015",
        "matematica",
        15,
        "Tabuada inicial (2, 5 e 10)",
        "Memorizar resultados de multiplicação por 2, 5 e 10 a partir de padrões.",
        ("MAT-014",),
        ("tabuada", "padrão", "multiplicar por dois", "multiplicar por cinco", "multiplicar por dez"),
        ("Multiplique por 2: dobre o número.", "Multiplique por 10: acrescente um zero.", "Multiplique por 5: metade de multiplicar por dez.", "Verifique com grupos iguais."),
        "Multiplicar por 2, 5 e 10 tem padrões fáceis de ver: por dois é dobrar, por dez é só mudar de casa, por cinco fica sempre entre esses dois.",
        ("6 vezes 10 = 60. 6 vezes 2 = 12. 6 vezes 5 = 30 (metade de 60).",),
        ("Calcule 7 vezes 2.", "Calcule 7 vezes 10.", "Calcule 7 vezes 5 usando o padrão."),
        (
            "Multiplicar por dez só desloca o número.",
            "Multiplicar por dois é dobrar.",
            "Cinco fica sempre no meio do caminho entre dois e dez.",
        ),
    ),
    _p(
        "MAT-016",
        "matematica",
        16,
        "Divisão como repartir",
        "Reconhecer divisão como repartir uma quantidade em partes iguais.",
        ("MAT-015",),
        ("dividir", "repartir", "partes iguais", "resto"),
        ("Escolha quantas partes.", "Reparta um a um em cada parte.", "Veja quanto cada parte recebeu.", "Veja se sobrou algo."),
        "Dividir é repartir uma quantidade em partes iguais. Se sobrar algo que não dá para repartir igualmente, isso é o resto.",
        ("12 balas para 3 crianças: cada uma recebe 4, sem sobrar nada.",),
        ("Reparta 10 lápis por 2 pessoas.", "Reparta 13 balas por 4 crianças e diga o resto.", "Calcule 15 dividido por 5."),
        (
            "Dividir é o inverso de juntar grupos iguais.",
            "Cada parte recebe a mesma quantidade.",
            "O resto é o que não cabe em nenhuma parte.",
        ),
    ),
    _p(
        "MAT-017",
        "matematica",
        17,
        "Metade e dobro",
        "Relacionar metade e dobro como divisão e multiplicação por dois.",
        ("MAT-016",),
        ("metade", "dobro", "dividir por dois", "multiplicar por dois"),
        ("Para o dobro, junte a quantidade com ela mesma.", "Para a metade, reparta em duas partes iguais.", "Verifique: o dobro da metade volta ao número original.", "Compare os dois resultados."),
        "O dobro de um número é multiplicá-lo por dois. A metade é dividi-lo por dois. Um desfaz o outro.",
        ("O dobro de 6 é 12. A metade de 12 é 6.",),
        ("Calcule o dobro de 9.", "Calcule a metade de 18.", "Explique por que o dobro da metade de um número volta ao mesmo número."),
        (
            "Dobro é multiplicar por dois (pacote MAT-014/015).",
            "Metade é dividir por dois (pacote MAT-016).",
            "Os dois são operações inversas.",
        ),
    ),
)


PACOTES_PORTUGUES: tuple[PacoteConhecimento, ...] = (
    _p(
        "POR-000",
        "portugues",
        0,
        "Som isolado",
        "Perceber sons separados, ainda sem significado.",
        (),
        ("som", "voz", "ouvir", "isolado"),
        ("Escute.", "Repita um som.", "Separe outro som.", "Não dê significado ainda."),
        "Antes da palavra, existe som. Um som isolado pode ser ouvido e repetido, mas ainda não aponta para uma ideia sozinho.",
        ("O som /a/ pode ser dito sozinho. Ele ainda não é uma frase nem uma palavra completa de sentido amplo.",),
        ("Faça o som /a/.", "Faça o som /m/.", "Diga se cada som está junto ou separado."),
        (
            "O ouvido percebe uma diferença.",
            "A boca repete essa diferença.",
            "O motor guarda o som como unidade antes do significado.",
        ),
    ),
    _p(
        "POR-001",
        "portugues",
        1,
        "Pausa e silêncio",
        "Perceber que pausas separam sons.",
        ("POR-000",),
        ("pausa", "silêncio", "separar"),
        ("Faça um som.", "Pare.", "Faça outro.", "Ouça a separação."),
        "A pausa ajuda a separar unidades. Sem pausa ou mudança perceptível, os sons viram uma massa difícil de organizar.",
        ("Dizer /a/ pausa /m/ é diferente de prolongar tudo sem corte.",),
        ("Bata palma, pare, bata de novo.", "Fale dois sons com pausa.", "Fale dois sons sem pausa e compare."),
        (
            "A pausa não é palavra.",
            "Mas ela organiza o fluxo.",
            "Na escrita, espaços e pontuação ajudam a representar separações.",
        ),
    ),
    _p(
        "POR-002",
        "portugues",
        2,
        "Letra",
        "Entender letra como sinal visual para representar som ou unidade escrita.",
        ("POR-001",),
        ("letra", "sinal", "alfabeto", "grafia"),
        ("Veja a letra.", "Diga o nome.", "Ligue ao som.", "Escreva."),
        "A letra é uma marca visual. Ela não é o som em si; ela representa uma unidade da escrita que pode se ligar a sons.",
        ("A letra A pode representar o som /a/ em muitas palavras.",),
        ("Escreva A.", "Aponte uma letra numa palavra.", "Diga uma palavra que começa com essa letra."),
        (
            "O som acontece no tempo.",
            "A letra fica no espaço da página.",
            "A escrita permite guardar e rever o som.",
        ),
    ),
    _p(
        "POR-003",
        "portugues",
        3,
        "Acento e ponto",
        "Reconhecer sinais que mudam leitura, pausa ou intenção.",
        ("POR-002",),
        ("acento", "ponto", "pontuação", "pausa"),
        ("Veja o sinal.", "Nomeie.", "Leia.", "Compare sem o sinal."),
        "Acentos e pontos são sinais pequenos, mas mudam a leitura. Acentos atuam sobre letras; pontuação organiza pausas e intenção.",
        ("avó e avô mudam pelo acento. 'Vai.' e 'Vai?' mudam pela pontuação.",),
        ("Compare avo, avó e avô.", "Leia uma frase com ponto.", "Transforme ponto final em interrogação."),
        (
            "A letra carrega uma base.",
            "O acento modifica essa base.",
            "A pontuação modifica o ritmo e o tipo de enunciado.",
        ),
    ),
    _p(
        "POR-004",
        "portugues",
        4,
        "Combinar letras",
        "Juntar letras em sílabas aproximadas e partes de palavra.",
        ("POR-003",),
        ("combinar", "sílaba", "dígrafo", "parte"),
        ("Pegue letras.", "Junte.", "Leia a parte.", "Junte outra parte."),
        "Quando letras se aproximam, formam blocos de leitura. Alguns blocos têm comportamento especial, como ch, lh e nh.",
        ("c + a forma ca. n + h forma nh, um dígrafo.",),
        ("Forme ma.", "Forme la.", "Ache ch numa palavra.", "Separe uma palavra em partes de fala."),
        (
            "Uma letra sozinha é uma peça.",
            "Duas ou mais letras podem formar bloco.",
            "O bloco ajuda a palavra nascer.",
        ),
    ),
    _p(
        "POR-005",
        "portugues",
        5,
        "Palavra",
        "Reconhecer palavra como forma separada que pode carregar sentido.",
        ("POR-004",),
        ("palavra", "forma", "separação", "sentido"),
        ("Leia a forma.", "Veja os espaços.", "Diga a palavra.", "Procure sentido."),
        "A palavra é uma unidade da língua. Ela tem forma escrita ou falada e pode apontar para um significado.",
        ("casa é uma palavra; ela aponta para uma ideia de habitação.",),
        ("Aponte uma palavra numa frase.", "Diga uma palavra curta.", "Diga uma palavra longa."),
        (
            "A palavra tem bordas.",
            "Na escrita, espaços ajudam a mostrar essas bordas.",
            "No dicionário, a palavra encontra lema e definição.",
        ),
    ),
    _p(
        "POR-006",
        "portugues",
        6,
        "Significado",
        "Ligar palavra a ideia, uso e definição.",
        ("POR-005",),
        ("significado", "ideia", "definição", "dicionário"),
        ("Escolha a palavra.", "Pergunte o que quer dizer.", "Veja o uso.", "Guarde a definição."),
        "Significado é o conteúdo que uma forma pode carregar. O dicionário ajuda, mas o contexto também participa.",
        ("manga pode ser fruta ou parte de roupa; o contexto decide.",),
        ("Defina casa.", "Use casa numa frase.", "Ache uma palavra com dois sentidos."),
        (
            "A forma sozinha pode ser ambígua.",
            "A definição dá um centro.",
            "O uso em frase escolhe o sentido mais provável.",
        ),
    ),
    _p(
        "POR-007",
        "portugues",
        7,
        "Frase",
        "Juntar palavras em enunciado com sentido.",
        ("POR-006",),
        ("frase", "enunciado", "sentido", "ordem"),
        ("Escolha palavras.", "Ordene.", "Leia.", "Veja se comunica algo."),
        "A frase organiza palavras para comunicar uma ideia. Pode ter verbo ou não, dependendo do tipo de enunciado.",
        ("Que dia bonito! é uma frase com sentido.",),
        ("Monte uma frase com casa.", "Troque a ordem das palavras.", "Veja se o sentido ficou claro."),
        (
            "Palavras soltas são peças.",
            "A frase põe as peças em relação.",
            "Pontuação ajuda a fechar o enunciado.",
        ),
    ),
    _p(
        "POR-008",
        "portugues",
        8,
        "Oração",
        "Reconhecer estrutura organizada em torno de verbo.",
        ("POR-007",),
        ("oração", "verbo", "sujeito", "predicado"),
        ("Ache o verbo.", "Veja quem participa.", "Separe sujeito.", "Separe predicado."),
        "A oração é uma construção com verbo. O verbo funciona como centro: em torno dele aparecem participantes, ações, estados e complementos.",
        ("A menina estuda. Verbo: estuda. Sujeito: A menina. Predicado: estuda.",),
        ("Ache o verbo em 'Os gatos comem'.", "Separe sujeito e predicado.", "Crie uma oração com ser."),
        (
            "Nem toda frase precisa ser oração.",
            "A oração precisa de verbo.",
            "Sujeito e predicado são uma primeira divisão funcional.",
        ),
    ),
    _p(
        "POR-009",
        "portugues",
        9,
        "Texto",
        "Encadear frases para construir uma mensagem maior.",
        ("POR-008",),
        ("texto", "ligação", "tema", "sequência"),
        ("Escolha um tema.", "Faça uma frase.", "Faça outra.", "Ligue as ideias."),
        "Texto é um conjunto organizado de enunciados. Ele mantém um tema, cria continuidade e guia o leitor.",
        ("A casa é grande. Ela fica perto da escola. As duas frases formam um pequeno texto.",),
        ("Escreva duas frases sobre um objeto.", "Ligue a segunda frase à primeira.", "Dê um título ao texto."),
        (
            "Uma frase comunica uma ideia.",
            "O texto organiza várias ideias.",
            "Coesão é a ligação visível entre partes.",
        ),
    ),
    _p(
        "POR-010",
        "portugues",
        10,
        "Sílaba tônica",
        "Reconhecer qual sílaba de uma palavra é pronunciada com mais força.",
        ("POR-009",),
        ("sílaba", "tônica", "força", "acento"),
        ("Separe a palavra em sílabas.", "Diga a palavra devagar.", "Ouça qual sílaba soa mais forte.", "Marque essa sílaba."),
        "Toda palavra com mais de uma sílaba tem uma sílaba mais forte, a tônica. Reconhecer essa força ajuda a ler e a saber quando usar acento.",
        ("Em 'casa', a força cai na primeira sílaba: CA-sa.",),
        ("Separe 'bola' em sílabas e diga qual é a tônica.", "Faça o mesmo com 'café'.", "Compare 'sábia' e 'sabia': o que muda?"),
        (
            "Sílaba é uma unidade sonora (pacote POR-004).",
            "Nem toda sílaba tem a mesma força.",
            "A sílaba tônica organiza o ritmo da palavra.",
        ),
    ),
    _p(
        "POR-011",
        "portugues",
        11,
        "Classes de palavras",
        "Reconhecer substantivo, verbo e adjetivo pela função na frase.",
        ("POR-010",),
        ("substantivo", "verbo", "adjetivo", "classe"),
        ("Ache a palavra que nomeia.", "Ache a palavra que indica ação ou estado.", "Ache a palavra que qualifica.", "Diga a classe de cada uma."),
        "Substantivo nomeia (casa, menino); verbo indica ação ou estado (correr, ser); adjetivo qualifica o substantivo (bonita, grande). Reconhecer a classe ajuda a entender a função de cada palavra na frase.",
        ("'O gato bonito dorme': gato é substantivo, bonito é adjetivo, dorme é verbo.",),
        ("Classifique as palavras de 'A menina estuda muito'.", "Dê um exemplo de substantivo, um de verbo e um de adjetivo.", "Troque o adjetivo de 'A casa grande' por outro."),
        (
            "Cada palavra tem uma função na frase.",
            "A classe gramatical é o nome dessa função.",
            "Saber a classe ajuda a montar frases corretas.",
        ),
    ),
    _p(
        "POR-012",
        "portugues",
        12,
        "Concordância",
        "Fazer determinante, substantivo e adjetivo concordarem em género e número.",
        ("POR-011",),
        ("concordância", "género", "número", "combinar"),
        ("Veja o género do substantivo.", "Veja o número do substantivo.", "Ajuste o determinante.", "Ajuste o adjetivo."),
        "Concordância é fazer as palavras combinarem entre si: se o substantivo é feminino e plural, o determinante e o adjetivo também precisam ser.",
        ("'As casas bonitas', não 'As casas bonito'.",),
        ("Corrija: 'o menina bonita'.", "Corrija: 'as gato preto'.", "Escreva uma frase com substantivo feminino plural e adjetivo concordando."),
        (
            "Cada palavra carrega género e número.",
            "As palavras relacionadas numa frase têm de combinar.",
            "Erro de concordância quebra a combinação, mesmo com sentido claro.",
        ),
    ),
    _p(
        "POR-013",
        "portugues",
        13,
        "Tempos verbais simples",
        "Reconhecer se uma ação está no presente, no passado ou no futuro.",
        ("POR-012",),
        ("tempo verbal", "presente", "passado", "futuro"),
        ("Ache o verbo.", "Pergunte quando a ação acontece.", "Diga presente, passado ou futuro.", "Troque o tempo e veja a forma mudar."),
        "O verbo muda de forma para mostrar quando a ação acontece: agora (presente), antes (passado) ou depois (futuro).",
        ("Estudo (presente), estudei (passado), vou estudar (futuro).",),
        ("Diga o tempo de 'ela cantou'.", "Mude 'eu como' para o passado.", "Mude 'nós jogamos' para o futuro."),
        (
            "O verbo é o centro da oração (pacote POR-008).",
            "A forma do verbo carrega uma informação de tempo.",
            "Mudar o tempo muda a forma, não o verbo em si.",
        ),
    ),
    _p(
        "POR-014",
        "portugues",
        14,
        "Sinônimos e antônimos",
        "Reconhecer palavras com sentido parecido e palavras com sentido oposto.",
        ("POR-013",),
        ("sinônimo", "antônimo", "sentido parecido", "sentido oposto"),
        ("Escolha uma palavra.", "Ache outra com sentido parecido.", "Ache outra com sentido oposto.", "Compare as três."),
        "Sinônimos são palavras diferentes com sentido parecido (feliz/contente). Antônimos têm sentido oposto (feliz/triste).",
        ("Grande é sinônimo de enorme e antônimo de pequeno.",),
        ("Dê um sinônimo de 'bonito'.", "Dê um antônimo de 'rápido'.", "Troque 'ela é feliz' por uma frase com sinônimo de feliz."),
        (
            "Palavras diferentes podem apontar para significados parecidos.",
            "Palavras diferentes também podem apontar para significados opostos.",
            "O dicionário (pacote POR-006) ajuda a comparar significados.",
        ),
    ),
    _p(
        "POR-015",
        "portugues",
        15,
        "Parágrafo",
        "Organizar várias frases relacionadas em um parágrafo com uma ideia central.",
        ("POR-014",),
        ("parágrafo", "ideia central", "organizar", "texto"),
        ("Escolha uma ideia central.", "Escreva uma frase que a apresente.", "Acrescente frases que a desenvolvam.", "Feche o parágrafo."),
        "Um parágrafo é um grupo de frases organizadas em torno de uma ideia central. Ele é a unidade que organiza um texto maior (pacote POR-009).",
        ("Ideia central: 'o cão é um bom animal de estimação'; frases seguintes explicam por quê.",),
        ("Escreva um parágrafo sobre a escola.", "Aponte a ideia central de um parágrafo dado.", "Divida um texto longo em dois parágrafos."),
        (
            "Uma frase comunica uma ideia (pacote POR-007).",
            "Várias frases relacionadas formam um parágrafo.",
            "Vários parágrafos relacionados formam um texto.",
        ),
    ),
    _p(
        "POR-016",
        "portugues",
        16,
        "Diálogo e discurso direto",
        "Reconhecer e escrever falas de personagens usando discurso direto.",
        ("POR-015",),
        ("diálogo", "discurso direto", "travessão", "fala"),
        ("Identifique quem fala.", "Marque a fala com travessão ou aspas.", "Mantenha a pontuação de quem fala.", "Volte ao texto narrado."),
        "Discurso direto reproduz exatamente a fala de alguém, geralmente marcada por travessão ou aspas.",
        ("— Estou com fome, disse o menino.",),
        ("Escreva uma fala de um personagem com travessão.", "Transforme uma frase narrada em discurso direto.", "Aponte quem fala num diálogo dado."),
        (
            "A narrativa conta o que acontece.",
            "O discurso direto mostra a fala exata de alguém.",
            "A pontuação marca onde a fala começa e termina.",
        ),
    ),
    _p(
        "POR-017",
        "portugues",
        17,
        "Pontuação além do ponto",
        "Usar vírgula, interrogação e exclamação para organizar sentido e entoação.",
        ("POR-016",),
        ("vírgula", "interrogação", "exclamação", "pontuação"),
        ("Veja se a frase pergunta, exclama ou só afirma.", "Escolha o sinal certo.", "Use vírgula para separar partes de uma enumeração ou pausa.", "Releia para confirmar o sentido."),
        "Além do ponto final (pacote POR-003), a vírgula separa partes de uma frase, a interrogação marca perguntas e a exclamação marca surpresa ou ênfase.",
        ("Comprei maçãs, peras e uvas. Que dia lindo! Vens amanhã?",),
        ("Pontue: 'Que susto'.", "Pontue: 'Vens à festa'.", "Separe com vírgulas: 'Trouxe lápis borracha e caderno'."),
        (
            "O ponto fecha uma afirmação simples.",
            "Interrogação e exclamação mudam a entoação da leitura.",
            "A vírgula organiza partes dentro da mesma frase.",
        ),
    ),
)


CURRICULOS: dict[str, tuple[PacoteConhecimento, ...]] = {
    "matematica": PACOTES_MATEMATICA,
    "portugues": PACOTES_PORTUGUES,
}
