version: '3.8'

networks:
  psf-network:
    external: true

services:
  psf-iaminy:
    build: .
    container_name: psf-app-psf-iaminy
    restart: always
    ports:
      - "8765:8765"
    networks:
      - psf-network
