# Configuration generated dynamically by PSF Platform
server {
    listen 80;
    server_name psf-iaminy.psf *.psf-iaminy.psf;

    location / {
        proxy_pass http://psf-iaminy:8765;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
